### ISSUE TITLE
Instructables

### ISSUE THREAD

**Issue by paytufo** [kswiorek/ble-ftms#1]
Did you do the instructables guide finaly?

**Comment by kswiorek** [comment]
I unfortunately didn't have the time, but I think you've motivated me enough to finally do this. I never actually suspected anyone would look at this. I if not a full instructable, I will publish some pictures this week.

**Comment by paytufo** [comment]
Thank you! I'm starting to learn some code but I'm pretty noob. I've many time searching this solution to my dumb bike trainer.  My idea is to build an open bike trainer for people who like DIY. A BLDC trainer like Tacx NEO or Wahoo. Your code could be the first step to develop this trainer.

**Comment by kswiorek** [comment]
I've made the instructable, I still need to upload some other files here, but the main thing is done [https://www.instructables.com/DIY-Indoor-Bike-Smart-Trainer/?cb=1604870523](url)

**Comment by doudar** [comment]
Oh wow....I've skimmed across your repo before but now that you did the instructable. Now I know what its for. lol.........check this out:

https://github.com/doudar/SmartSpin2k-PlatformIO

I bet we could have saved each other a bunch of time. I've been wracking my head on that buggy ESP bluetooth library for a year in my spare time. 

Maybe we should collaborate? :)

**Comment by kswiorek** [comment]
Nice project! Far more professional than mine... It looks like you've got everything figured out. I will gladly help, but I'm not much of a coder - this whole thing is bodged together from some examples. I focused more on the physics of a realistic simulation. In theory this should be just as a normal bike - it even has the correct ratios of gears taken from a real road bike. 
I also prefer to mount everything on one PCB - the wires often break and short, it always annoys me.

**Comment by doudar** [comment]
I would *love* to see a carrier PCB if you thought it was possible. Possibly with an integrated dc-dc converter. I don't really have issues with wires breaking if they're done correctly but they do make assembly a pain. 

Anyway, awesome project of yours too! I wouldn't have had any idea on where to start with that load cell stuff that you did.
